language: python

python:
  - 3.6

install:
  - sudo apt-get update
  - sudo apt-get -y install python-pip
  - sudo pip install --upgrade pip
  - pip install --upgrade pip
  - pip install pep8
  - pip install pylint

script:
  - python -m doctest *.py
  - pylint *.py
  - pep8 *.py
